# Generated by Django 2.1.7 on 2019-07-07 15:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 7, 15, 51, 37, 516349, tzinfo=utc)),
        ),
    ]
