# Generated by Django 2.1.7 on 2019-07-27 11:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190725_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepost',
            name='total_view',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 27, 11, 44, 12, 348136, tzinfo=utc)),
        ),
    ]
