# Generated by Django 2.1.7 on 2019-07-27 11:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190727_1144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlepost',
            old_name='total_view',
            new_name='total_views',
        ),
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 27, 11, 50, 15, 217829, tzinfo=utc)),
        ),
    ]
